# Generated by Django 3.2.21 on 2024-01-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(default='message', max_length=500)),
                ('sender', models.CharField(max_length=100)),
                ('email', models.EmailField(default='email@email.com', max_length=100)),
            ],
        ),
    ]
