# Generated by Django 3.2.21 on 2024-01-14 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0002_alter_likemodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
