# Generated by Django 3.2.21 on 2024-01-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_likemodel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='dislikes',
        ),
    ]
