# Generated by Django 3.2.21 on 2024-01-19 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0005_remove_likemodel_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
