# Generated by Django 3.2.21 on 2024-01-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={},
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='created_at',
        ),
    ]
