# Generated by Django 3.2.21 on 2024-01-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_testimonials_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='slug',
        ),
    ]
