# Generated by Django 3.2.21 on 2024-01-25 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimonials', '0004_auto_20240110_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='organizer',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
