# Generated by Django 3.2.21 on 2024-01-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0007_alter_testimonials_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='organizer',
        ),
    ]
