# Generated by Django 3.2.21 on 2023-12-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/images/default.jpg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
