# Generated by Django 3.2.21 on 2024-01-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='Rating',
        ),
        migrations.AddField(
            model_name='rate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default='0'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='products.product'),
        ),
    ]
