# Generated by Django 3.2.21 on 2024-01-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240121_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rate',
        ),
    ]
